
# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
    - staging
    - develop
  pull_request:
    branches:
    - master
    - staging
    - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.6' # The Go version to download (if necessary) and use.
    
    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        
    # Run build of the application
    - name: Run build
      # env:
      #   GOOS: linux
      #   GOARCH: amd64
      run: |
        mkdir build/
        make
      # go build -o build/k8s-client .

    # Run vet & lint on the code
    - name: Run vet & lint
      run: |
        go vet .
        golint .
    
    - name: Save build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build/k8s-client-linux
        retention-days: 1
    # Run testing on the code
    # - name: Run testing
    #   run: cd test && go test -v
    
    # # Send slack notification
    # - name: Send slack notification
    #   uses: 8398a7/action-slack@v3
    #   with:
    #     author_name: "k8s-client cicd action"
    #     status: ${{ job.status }}
    #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
    #   if: always() # Pick up events even if the job fails or is canceled.

  # The "deploy" workflow
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [build] # Only run this workflow when "build" workflow succeeds
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} # Only run this workflow if it is master branch on push event
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: build/k8s-client-linux
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v1

    # Deploy to Docker registry
    - name: Deploy to Docker registry
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/k8s-client:latest
        #tag_with_ref: true
